In [1]:
import numpy as np

In [46]:
A = np.array([[1,2,3,4], [5,6,7,8]])

In [47]:
A.size

8

In [48]:
A.shape

(2, 4)

In [49]:
A = np.insert(A, 1, [9,10,11,12], axis=0)

In [50]:
print(A)

[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]]


In [51]:
A = np.insert(A, 1, [13,14,15], axis=1)

In [52]:
print(A)

[[ 1 13  2  3  4]
 [ 9 14 10 11 12]
 [ 5 15  6  7  8]]
